# Generated by Django 4.2.19 on 2025-03-08 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='chargers',
        ),
        migrations.AddField(
            model_name='station',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='admin_stations', to=settings.AUTH_USER_MODEL),
        ),
    ]
