# Generated by Django 4.2.19 on 2025-03-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_station_chargers_station_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='charger',
            name='activity',
            field=models.CharField(default='Idle', max_length=50),
        ),
    ]
