# Generated by Django 4.2.19 on 2025-03-12 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_charger_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charger',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chargers', to='api.station'),
        ),
    ]
