# Generated by Django 4.2.19 on 2025-03-08 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_customuser_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_admin',
        ),
    ]
